// Akce pro Moduly
export const MODULE_UPDATING = "MODULE_UPDATING";
export const MODULE_UPDATED = "MODULE_UPDATED";
export const MODULE_FAILED = "MODULE_FAILED";
export const MODULE_HIDE_READED_ITEMS = "MODULE_HIDE_READED_ITEMS";
export const MODULE_ADD_REDED_ITEM_ID = "MODULE_ADD_REDED_ITEM_ID";

// Board filter
export const BOARD_SET_TYPE = "BOARD_SET_TYPE";
export const BOARD_SET_SOURCE = "BOARD_SET_SOURCE";
export const BOARD_OPEN_MODAL = "BOARD_OPEN_MODAL";
export const BOARD_RESET = "BOARD_RESET";

// Mapa upozornení filter
export const NOTICES_SET_TYPES = "NOTICES_SET_TYPES";

// Tématické mapy
export const THEMATIC_MAP_SET_TYPES = "THEMATIC_MAP_SET_TYPES";
export const THEMATIC_MAP_OPEN_MODAL = "THEMATIC_MAP_OPEN_MODAL";
export const THEMATIC_MAP_RESET = "THEMATIC_MAP_RESET";

// Places
export const PLACES_CATEGORIES_CLEAR = "PLACES_CATEGORIES_CLEAR";
export const PLACES_SET_CATEGORY = "PLACES_SET_CATEGORY";
export const PLACES_OPEN_MODAL = "PLACES_OPEN_MODAL";
export const PLACES_RESET = "PLACES_RESET";
export const PLACES_SET_ORDER_BY = "PLACES_SET_ORDER_BY";
export const PLACES_SET_LOCATION = "PLACES_SET_LOCATION";

// Navigace
export const SET_FOCUSED_ROUTE = "SET_FOCUSED_ROUTE";

// Kalendář akcí
export const EVENTS_SET_CATEGORY = "EVENTS_SET_CATEGORY";
export const EVENTS_SET_DATE_CHOICE = "EVENTS_SET_DATE_CHOICE";
export const EVENTS_OPEN_MODAL = "EVENTS_OPEN_MODAL";
export const EVENTS_RESET = "EVENTS_RESET"

// Settings
export const TOGGLE_NOTIFICATION_ENABLE = "TOGGLE_NOTIFICATION_ENABLE";
export const SET_GPS_NOTIFICATION = "SET_GPS_NOTIFICATION";
export const SET_NOTIFICATION_TOKEN = "SET_NOTIFICATION_TOKEN";
export const SET_UUID = "SET_UUID";
